= Overview

Produce messages to and consume messages from a Kafka cluster using the Kotlin
version of Java Producer and Consumer, and Kafka Streams API.

= Documentation

You can find the documentation and instructions for running this Kotlin example
at
https://docs.confluent.io/platform/current/tutorials/examples/clients/docs/kotlin.html?utm_source=github&utm_medium=demo&utm_campaign=ch.examples_type.community_content.clients-ccloud[https://docs.confluent.io/platform/current/tutorials/examples/clients/docs/kotlin.html]



Producer

./gradlew runApp -PmainClass="io.confluent.examples.clients.cloud.ProducerExample" \
     -PconfigPath="./java.config" \
     -Ptopic="test1"

Consumer
./gradlew runApp -PmainClass="io.confluent.examples.clients.cloud.ConsumerExample"\
     -PconfigPath="./java.config"\
     -Ptopic="test1"


Streams
./gradlew runApp -PmainClass="io.confluent.examples.clients.cloud.StreamsExample" \
     -PconfigPath="$HOME/.confluent/java.config" \
     -Ptopic="test1"

Aggregator

 ./gradlew runApp -PmainClass="com.reaktor.kafka.intro.aggregate.AggregatingReduce" \
     -PconfigPath="./java.config" \
     -PinputTopic="player-moves-0" \
     -PoutputTopic="screens-0"